# Set these if you wish to override the default chart name / fullname. By default, the release name (which is the Application name when deploying with ArgoCD)
# is used as the app name, and the fullname is "<release-name>-<chart-name>"
# nameOverride: ""
# fullnameOverride: ""

# using one replica since state is in-memory
replicaCount: 1

image:
  repository: ghcr.io/q29vba/linker-url-shortener
  pullPolicy: IfNotPresent
  # future proposal: CI pipeline or ArgoCD image updater to automate tag updates
  tag: "v1"

# injected into the container as the BASE_URL environment variable
baseUrl: "http://default.domain" # override in argocd Application values with the correct URL for your environment

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations: {}
    # for production, would typically add annotations here, e.g:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod" # for certificates management with cert-manager
    # nginx.ingress.kubernetes.io/ssl-redirect: "true" # to enforce HTTPS, if using nginx ingress controller
  # If host is left empty, the helm chart will derive it from the .Values.baseUrl
  host: ""
  tls: []
  # To enable TLS, create appropriate secret, uncomment and configure:
  # - secretName: linker-tls
  #   hosts:
  #     - linker.local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    memory: "128Mi"

# failed liveness probe causes kubelet to restart the container
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 15
  failureThreshold: 3

# failed readiness probe removes pod from the service's endpoint list.
# would ideally configure a spereate endpoint for readiness.
# since both reach /health, configured to fail before the liveness probe to allow time for
# the app to recover without a restart, if possible (e.g. if the app is temporarily overloaded)
# but to still prevent sending traffic to an unresponsive pod.
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

# pod wide security context
podSecurityContext: # matching Dockerfile USER 1001
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001 # Kubelet sets volume ownership to this GID and adds it as a group, allows the app running as non-root to read/write to mounted volumes

# container specific security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true # since the app doesn't need to write to the filesystem
  capabilities:
    drop:
      - ALL

# since readOnlyRootFilesystem and gunicorn needs a writable /tmp for its worker process files.
extraVolumes:
  - name: tmp-dir
    emptyDir: {}
extraVolumeMounts:
  - name: tmp-dir
    mountPath: /tmp
