{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "linker.fullname" . }}
  labels:
    {{- include "linker.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- /* Extract the domain from baseUrl */}}
    {{- $domain := .Values.baseUrl | replace "https://" "" | replace "http://" "" | splitList "/" | first | splitList ":" | first }}

    {{- /* Use ingress.host if provided, otherwise use the derived domain */}}
    - host: {{ default $domain .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "linker.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}